concommand.Add("Log4g_CoreTest_CreateLoggerContext", function()
	Log4g.Core.LoggerContext.Register("context_test_a")
	Log4g.Core.LoggerContext.Register("context_test_b")
	Log4g.Core.LoggerContext.Register("context_test_c")
end)

concommand.Add("Log4g_CoreTest_RemoveLoggerContext", function()
	Log4g.Core.LoggerContext.Get("context_test_a"):Terminate()
	Log4g.Core.LoggerContext.Get("context_test_b"):Terminate()
	Log4g.Core.LoggerContext.Get("context_test_c"):Terminate()
end)

concommand.Add("Log4g_CoreTest_ShowAllLoggerContext", function()
	PrintTable(Log4g.Core.LoggerContext.GetAll())
end)
