concommand.Add("Log4g_CoreTest_CreateLogger", function()
    local ctx = Log4g.API.LoggerContextFactory.GetContext("TestLoggerHierarchyCtx")
    Log4g.Core.Logger.Create("A", ctx, Log4g.Level.GetLevel("ALL"))
    Log4g.Core.Logger.Create("A.B", ctx, Log4g.Level.GetLevel("ALL"))
    Log4g.Core.Logger.Create("A.B.C", ctx, Log4g.Level.GetLevel("ALL"))
    Log4g.Core.Logger.Create("A.B.C.D", ctx, Log4g.Level.GetLevel("ALL"))
    local AB = ctx:GetLogger("A.B")
    local ABC = ctx:GetLogger("A.B.C")
    local ABCD = ctx:GetLogger("A.B.C.D")
    print("A.B's parent: " .. AB:GetLoggerConfig():GetParent())
    print("A.B.C's parent: " .. ABC:GetLoggerConfig():GetParent())
    print("A.B.C.D's parent: " .. ABCD:GetLoggerConfig():GetParent())
    print("if 'ConsoleOut' add success: " .. tostring(ABC:GetLoggerConfig():AddAppender(Log4g.Core.Appender.CreateConsoleAppender("ConsoleOut"))))
    print("if 'ConsoleOut2' add success: " .. tostring(ABC:GetLoggerConfig():AddAppender(Log4g.Core.Appender.CreateConsoleAppender("ConsoleOut2"))))
    print("A.B.C's loggerconfig appenderref:")
    PrintTable(ABC:GetLoggerConfig():GetAppenderRef())
    print("TestLoggerHierarchyCtx's configuration's appenders all:")
    PrintTable(Log4g.Core.LoggerContext.Get("TestLoggerHierarchyCtx"):GetConfiguration():GetAppenders())
end)

concommand.Add("Log4g_CoreTest_RemoveLoggerConfigAppenders", function()
    local ctx = Log4g.API.LoggerContextFactory.GetContext("TestLoggerHierarchyCtx")
    local ABC = ctx:GetLogger("A.B.C")
    ABC:GetLoggerConfig():ClearAppenders()
end)