local POOL = Log4g.API.LoggerContextFactory.GetContext("POOL", true)
local BOOK = Log4g.Core.Config.LoggerConfig.create("BOOK", POOL:GetConfiguration(), Log4g.Core.Level.getLevel("TRACE"))
BOOK:AddAppender(Log4g.Core.Appender.ConsoleAppender.createConsoleAppender("TestAppender", Log4g.Core.Layout.PatternLayout.createDefaultLayout("TestLayout")))
local RUNNER = Log4g.Core.Logger.create("BOOK", POOL, BOOK)
RUNNER:Trace("Test TRACE message")
print(RUNNER:IsAdditive())
POOL:Terminate()